Onnx models
bioinf-mcb/Metagenomic-DeepFRI pull request #44
Opened 2023-04-29 19:03 UTC by valentynbez

- Models ported to ONNX
- Comparison notebook and convert code attached to the project
- `Predictior` rewritten as a part of the package, DeepFRI submodule removed
- tensorflow & biopython dependencies removed
- Automatic switches between GPU and CPU, multithreading on CPU
- new CLI 
- project structure improvements

2023-05-01 21:41 UTC, valentynbez commented
This is the final commit on this PR. This is a working version with onnx models.
Ready to merge from my side.

2023-05-04 04:34 UTC, SoliareofAstora requested changes
Piękne zmiany. Nie mogę się doczekać merge

2023-05-04 04:34 UTC, SoliareofAstora commented on mDeepFRI/CPP_lib/load_contact_maps.cpp
> +<<<<<<< HEAD
unmerged conflict

2023-05-04 04:34 UTC, SoliareofAstora commented on mDeepFRI/__init__.py
> +    "https://huggingface.co/crusher083/mDeepFRI/resolve/main/DeepCNN-MERGED_bp.onnx",
How about move repeating pattern of huggingface url to some constant?

2023-05-04 04:34 UTC, SoliareofAstora commented on mDeepFRI/cli.py
> +def main(ctx, debug):
I'm more used to main function definition to be placed at the bottom of the file

2023-05-04 04:34 UTC, SoliareofAstora commented on mDeepFRI/predict.py
> +    def save_file(self, output_fn: str, delimiter: str, quotechar: str = '"'):
I propose make it private

2023-05-04 04:34 UTC, SoliareofAstora commented on weight_convert/convert_models2onnx.py
> +    model_path = args.weights
please define main() function

2023-05-07 10:42 UTC, SoliareofAstora approved these changes

2023-05-07 10:47 UTC, merged